apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: binpacking-scheduler-annotation
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
      - apiGroups: ["*"]
        kinds: ["Pod"]
    namespaces: ["default"]
  location: "spec.schedulerName"
  parameters:
    assign:
      value: "bp-scheduler"
